apiVersion: apps/v1
kind: Deployment
metadata:
  name: samstore
  labels:
    app: samstore
spec:
  template:
    spec:
      containers:
      - name: samstore
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "500m"

