apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: sam-dev

patchesStrategicMerge:
- deploy.yaml


# images:
# - name: nogada/samstore:latest
#   newTag: v1.0