apiVersion: apps/v1
kind: Deployment

spec:
  template:
    spec:
      containers:
      - name: store
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "500m"

